chore: interim update on scripts and README

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -2,24 +2,18 @@
 # execute all of the steps necessary to build the project
 set -e #-x
 
+usage() {
+  echo "usage: $0 [compile|test|package|docker]"
+}
+
 build_cmd=build               # Overridden by -c or --cmd
 ROOT_DIR="$(cd "$(dirname "$0")/.."; pwd)"
 
-# option support: https://stackoverflow.com/a/28466267
-# supported option syntaxes include:
-# `x`  -x
-# `x:` -x value or --x-long-name=value
-#
-# unsupported syntax is:
-# --xoption value
-#
-# NOTE: if requiring an option-value with `:`,
-# please specify `needs_arg` first in the case opts below
-#
-die() { echo "$*" >&2; exit 2; }  # complain to STDERR and exit with error
+
+die() { echo "$*" >&2; usage; exit 2; }  # complain to STDERR and exit with error
 needs_arg() { if [ -z "$OPTARG" ]; then die "No arg for --$OPT option"; fi; }
 
-while getopts c:-: OPT; do  # allow -a, -b with arg, -c, and -- "with arg"
+while getopts c:-: OPT; do  # allow -c with arg and -- "with arg"
   # support long options: https://stackoverflow.com/a/28466267/519360
   if [ "$OPT" = "-" ]; then   # long option: reformulate OPT and OPTARG
     OPT="${OPTARG%%=*}"       # extract long option name
