chore: checkpoint on status

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -4,16 +4,26 @@
 
 # the list of tools required to be installed to interact with this repo
 # this is meant to verify what is also in the ./README.md#environment-setup section
-TOOLS=(java)
+TOOLS=(java docker)
+
+log() {
+  echo "[bin/setup] ${@}"
+}
 
 verify_tool() {
-  if ! command -v $1 &> /dev/null
-  then
-      echo "'$1' could not be found"
+  if ! command -v $1 &> /dev/null; then
+      log "'$1' could not be found"
       exit 1
+  else
+    log "verified: ${@}"
   fi
 }
 
+log "verifying required tools are installed"
 for tool in "${TOOLS[@]}"; do
   verify_tool $tool
 done
+echo ""
+
+log "setting up database"
+$(dirname $0)/setup-db start
