just another snapshot in time

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -3,17 +3,22 @@
 set -e #-x
 
 usage() {
-  echo "usage: $0 [compile|test|package|docker]"
+  echo "usage: $0 [-h|--help] [compile|test|package|docker]"
+  echo ""
+  echo "[-h|--help]      print this help text"
 }
 
-build_cmd=build               # Overridden by -c or --cmd
+# script variables and defaults
 ROOT_DIR="$(cd "$(dirname "$0")/.."; pwd)"
+build_cmd=build               # Overridden by -c or --cmd
+DEBUG_OPTS=""
 
 
-die() { echo "$*" >&2; usage; exit 2; }  # complain to STDERR and exit with error
+# process command-line options (if any)
+die() { echo "$*" >&2; echo ""; usage; exit 2; }  # complain to STDERR and exit with error
 needs_arg() { if [ -z "$OPTARG" ]; then die "No arg for --$OPT option"; fi; }
 
-while getopts c:-: OPT; do  # allow -c with arg and -- "with arg"
+while getopts h-: OPT; do  # allow -h and -- "with arg"
   # support long options: https://stackoverflow.com/a/28466267/519360
   if [ "$OPT" = "-" ]; then   # long option: reformulate OPT and OPTARG
     OPT="${OPTARG%%=*}"       # extract long option name
@@ -21,7 +26,6 @@ while getopts c:-: OPT; do  # allow -c with arg and -- "with arg"
     OPTARG="${OPTARG#=}"      # if long option argument, remove assigning `=`
   fi
   case "$OPT" in
-    c )            needs_arg; build_cmd=$OPTARG ;;
     h | help )     usage; exit 0 ;;
     \? )           usage; exit 2 ;;  # bad short option (error reported via getopts)
     * )            die "Illegal option --$OPT" ;;            # bad long option
@@ -29,15 +33,37 @@ while getopts c:-: OPT; do  # allow -c with arg and -- "with arg"
 done
 shift $((OPTIND-1)) # remove parsed options and args from $@ list
 
+package() {
+  cd ${ROOT_DIR}
+  ${ROOT_DIR}/gradlew
+}
 
-BLABLAH=$1
 
-####
-#
-#
-echo "$ROOT_DIR"
-echo "$build_cmd"
-echo "$BLABLAH"
+# process input arguments
+CMD=$1
+echo "command: $CMD"
+case "$CMD" in
+  compile )      echo "compile" ;;
+  test )         echo "test" ;;
+  package )      echo "package" ;;
+  docker )       echo "docker" ;;
+  \? )           usage; exit 2 ;;  # bad short option (error reported via getopts)
+  * )            die "Missing or illegal build command: '${CMD}'" ;;            # bad long option
+esac
 
-#${ROOT_DIR}/gradlew -Dorg.gradle.project.buildDir=$ROOT_DIR $build_cmd
+
+
+./gradlew --build-cache :service:jibDockerBuild \
+./gradlew --build-cache build -x test
+./gradlew --build-cache build -x test -x spotlessCheck
+./gradlew --build-cache :service:build -x test
+./gradlew --build-cache bootRun | tee application.log &
+./gradlew --build-cache srcclr
+./gradlew --build-cache test jacocoTestReport
+./gradlew --build-cache runTest --args="suites/${{ needs.test-env.outputs.test-env }}/FullIntegration.json build/reports"
+./gradlew --build-cache runTest --args="suites/local/FullIntegration.json build/reports"
+./gradlew --build-cache uploadResults --args="CompressDirectoryToTerraKernelK8S.json build/reports"
+#        run: ./gradlew --build-cache sonar
+
+
 
