chore: cleanup from self-PR review

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -3,22 +3,23 @@
 set -e #-x
 
 usage() {
-  echo "usage: $0 [-h|--help] COMMAND"
-  echo ""
-  echo "[-h|--help]      print this help text"
-  echo ""
-  echo "COMMAND is one of the following:"
-  echo "- test           execute the tests"
-  echo "- project        the default build command"
-  echo "- docker         build a docker image"
+  cat <<-'EOF'
+usage: build [-t|--skip-tests] [-h|--help] BUILDTYPE
+
+[-t|--skip-tests]       skip running unit tests;
+                        this is used in the CI process
+[-h|--help]             print this help text
+
+BUILDTYPE is one of the following:
+- project               the default build command
+- docker                build a docker image
+EOF
 }
 
 # script variables and defaults
 source $(dirname $0)/init.sh
+skip_tests=""
 
-DEBUG_OPTS=""
-
-log_debug "before: $@"
 
 # process command-line options (if any)
 die() { log_error "$*" >&2; echo ""; usage; exit 2; }  # complain to STDERR and exit with error
@@ -32,26 +33,27 @@ while getopts h-: OPT; do  # allow -h and -- "with arg"
     OPTARG="${OPTARG#=}"      # if long option argument, remove assigning `=`
   fi
   case "$OPT" in
-    h | help )     usage; exit 0 ;;
-    \? )           usage; exit 2 ;;  # bad short option (error reported via getopts)
-    * )            die "Illegal option --$OPT" ;;            # bad long option
+    t | skip-tests )       skip_tests="-x test" ;;
+    h | help )             usage; exit 0 ;;
+    \? )                   usage; exit 2 ;;  # bad short option (error reported via getopts)
+    * )                    die "Illegal option --$OPT" ;;            # bad long option
   esac
 done
 shift $((OPTIND-1)) # remove parsed options and args from $@ list
 
 
 # process positional arguments (if any)
-COMMAND=$1
+BUILDTYPE=$1
 shift 1
 
 # use all trailing arguments as caveats to BUILD command
 GRADLE_BUILD_OPTS=${GRADLE_BUILD_OPTS:-"$@"}
-log_debug "gradle build opts: ${GRADLE_BUILD_OPTS}"
+log_debug "add'l commandline gradle build opts: ${GRADLE_BUILD_OPTS}"
 
 
 build_project() {
   cd "${ROOT_DIR}"
-  ./gradlew ${GRADLE_OPTS} build ${GRADLE_BUILD_OPTS}
+  ./gradlew ${GRADLE_OPTS} build ${skip_tests} ${GRADLE_BUILD_OPTS}
 #./gradlew --build-cache build -x test
 #./gradlew --build-cache build -x test -x spotlessCheck
 #./gradlew --build-cache :service:build -x test
@@ -67,7 +69,7 @@ build_docker() {
   cd "${ROOT_DIR}"
   ./gradlew ${GRADLE_OPTS} :service:jibDockerBuild \
             --image="${DOCKER_IMAGE_NAME_AND_TAG}" \
-            -Djib.console=plain
+            -Djib.console=plain ${skip_tests}
 
   # the latest tag will allow `docker compose` to work correctly for developers
   if [ -z "$CI" ]; then
@@ -76,8 +78,8 @@ build_docker() {
 #./gradlew --build-cache :service:jibDockerBuild \
 }
 
-case "$COMMAND" in
-  project )      build_project ;;
-  docker )       build_docker ;;
-  * )            die "Missing or invalid positional command: '${COMMAND}'" ;;
+case "$BUILDTYPE" in
+  project )       build_project ;;
+  docker )        build_docker ;;
+  * )             die "Missing or invalid positional command: '${BUILDTYPE}'" ;;
 esac
